### ISSUE TITLE
Separate rendering & parsing

### ISSUE THREAD

**Issue by norangi** [norangi/jnote-mobile#5]
[j-markdown.js](https://github.com/norangi/jnote-mobile/blob/markdown-heading/jnote/markdown/j-markdown.js) contains both parsing & rendering. This makes the code gets too long and slightly difficult to understand.

## Todo
- [ ] Create a branch(`markdown-split`) from `markdown-heading`.
- [ ] From the new branch, create another file (`j-rendering.js`)
- [ ] This file contains a new class 
- [ ] Make sure split works great
- [ ] Merge `markdown-split` and `markdown-heading`.
